networks:
  esd-net:
    driver: bridge
    name: esd-net

services:

  ###################################
  # Drink: The Drink Menu microservice
  ###################################
  drink_menu:
    build:
      context: ./drink_menu
      dockerfile: drink_menu.Dockerfile
    image: jiaxuanlai/drink_menu:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/drink_menu
      #dbURL: mysql+pymysql://root:@host.docker.internal:3306/drink_menu
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"
    networks:
      - esd-net     

  ###################################
  # Drink: The Drink Ingredient microservice
  ###################################
  drink_ingredients:
    build:
      context: ./drink_ingredients
      dockerfile: drink_ingredients.Dockerfile
    image: jiaxuanlai/drink_ingredients:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/drink_ingredients
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"
    networks:
      - esd-net   

  ###################################
  # Drink: The Drink Customisation microservice
  ###################################
  drink_customisation:
    build:
      context: ./drink_customisation
      dockerfile: drink_customisation.Dockerfile
    image: jiaxuanlai/drink_customisation:esd
    restart: always
    environment:
      #dbURL: mysql+pymysql://root:@host.docker.internal:3306/customisation
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/customisation
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"
    networks:
      - esd-net   

  ###################################
  # Inventory: The Inventory microservice
  ###################################
  inventory:
    build:
      context: ./inventory
      dockerfile: inventory.Dockerfile
    ports:
      - "5000:5000"
    image: amritad/inventory:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory
      PYTHONUNBUFFERED: 1
    networks:
      - esd-net

  ###################################
  # Outlets: The Outlet microservice
  ###################################
  outlet:
    build:
      context: ./Outlets
      dockerfile: outlet.Dockerfile
    image: amritad/outlet:esd
    ports:
      - "5001:5001"
    restart: always
    environment:
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/outlet
      - PYTHONUNBUFFERED=1
    networks:
      - esd-net

###################################
  # Login: The Login microservice
  ###################################
  login:
    build:
      context: ./Login   
      dockerfile: login.Dockerfile 
    image: amritad/login:esd
    ports:
      - "5019:5019"
    restart: always
    environment:
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/profile
      - PYTHONUNBUFFERED=1
    networks:
      - esd-net

 
  ###################################
  # Cart: The Cart microservice
  ###################################
  cart:
    build:
      context: ./Cart
      dockerfile: cart.Dockerfile
    image: jiaxuanlai/cart:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5015:5015"
    networks:
      - esd-net    

  
  ###################################
  # Cart_items: The Cart_items microservice
  ###################################
  cart_items:
    build:
      context: ./Cart_items
      dockerfile: cart_items.Dockerfile
    image: jiaxuanlai/cart_items:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart_items
      PYTHONUNBUFFERED: 1
    ports:
      - "5016:5016"
    networks:
      - esd-net 

  ###################################
  # Cart_items_customisation: The Cart_items_customisation microservice
  ###################################
  cart_items_customisation:
    build:
      context: ./Cart_Items_Customisation
      dockerfile: cart_items_customisation.Dockerfile
    image: jiaxuanlai/cart_items_customisation:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart_items_customisation
      PYTHONUNBUFFERED: 1
    ports:
      - "5017:5017"
    networks:
      - esd-net     

  ###################################
  # Profile: The Profile microservice
  ###################################
  profile:
    build:
      context: ./Profile
      dockerfile: profile.Dockerfile
    image: jiaxuanlai/profile:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/profile
      PYTHONUNBUFFERED: 1
    ports:
      - "5018:5018"
    networks:
      - esd-net      

  ###################################
  # StripePayment: The StripePayment microservice
  ###################################
  payment:
    build:
      context: ./StripePayment
      dockerfile: payment.Dockerfile
    image: jiaxuanlai/payment:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"
    networks:
      - esd-net

  ###################################
  # Payment_log: The Payment_log microservice
  ###################################
  payment_log:
    build:
      context: ./payment_log
      dockerfile: payment_log.Dockerfile
    image: shashass/payment_log:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/payment_log
      PYTHONUNBUFFERED: 1
    ports:
      - "5123:5123"
    networks:
      - esd-net


###################################
  # Add to Cart: The Add to Cart composite microservice
  ###################################
  CartCompositeServie:
    build:
      context: ./CartCompositeServie
      dockerfile: CartCompositeServie.Dockerfile
    image: jiaxuanlai/cartcompositeservie:esd
    restart: always
    depends_on:
      - cart
      - cart_items
      - cart_items_customisation
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"
    networks:
      - esd-net     

 ###################################
  # Payment Composite: The Payment composite microservice
  ###################################
  PaymentComposite:
    build:
      context: ./PaymentCompositeService
      dockerfile: paymentComposite.Dockerfile
    image: jiaxuanlai/payment-composite:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5300:5300"
    networks:
      - esd-net  

  ###################################
  # Twilio: The Twilio microservice
  ###################################
  Twilio:
    build:
      context: ./Twilio
      dockerfile: twilio.Dockerfile
    image: jiaxuanlai/twilio:esd
    restart: always
    env_file: 
      - ./Twilio/.env  # Path to your .env file relative to the compose file
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "6000:6000"
    networks:
      - esd-net