## PLEASE CHANGE THE DOCKERID TO YOUR OWN!!!
## REPLACE ALL THE SHASHASS WITH YOUR OWN DOCKERID:)

networks:
  esd-net:
    driver: bridge
    name: esd-net

services:

  ###################################
  # Drink: The Drink microservice
  ###################################
  drink:
    build:
      context: ./drink
      dockerfile: drink.Dockerfile
    image: jiaxuanlai/drink:esd
    restart: always
    environment:
      # dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
    networks:
      - esd-net      


  ###################################
  # Inventory: The Inventory microservice
  ###################################
  inventory:
    build:
      context: ./inventory
      dockerfile: inventory.Dockerfile
    ports:
      - "5000:5000"
    image: amritad/inventory:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory
      PYTHONUNBUFFERED: 1
    networks:
      - esd-net

  ###################################
  # Outlets: The Outlet microservice
  ###################################
  outlet:
    build:
      context: ./Outlets
      dockerfile: outlet.Dockerfile
    image: amritad/outlet:esd
    ports:
      - "5001:5001"
    restart: always
    environment:
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/outlet
      - PYTHONUNBUFFERED=1
    networks:
      - esd-net
 
  ###################################
  # Cart: The Cart microservice
  ###################################
  cart:
    build:
      context: ./Cart
      dockerfile: cart.Dockerfile
    image: jiaxuanlai/cart:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5015:5015"
    networks:
      - esd-net    

  
  ###################################
  # Cart_items: The Cart_items microservice
  ###################################
  cart_items:
    build:
      context: ./Cart_items
      dockerfile: cart_items.Dockerfile
    image: jiaxuanlai/cart_items:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart_items
      PYTHONUNBUFFERED: 1
    ports:
      - "5016:5016"
    networks:
      - esd-net 

  ###################################
  # Cart_items_customisation: The Cart_items_customisation microservice
  ###################################
  cart_items_customisation:
    build:
      context: ./Cart_Items_Customisation
      dockerfile: cart_items_customisation.Dockerfile
    image: jiaxuanlai/cart_items_customisation:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart_items_customisation
      PYTHONUNBUFFERED: 1
    ports:
      - "5017:5017"
    networks:
      - esd-net     

  ###################################
  # Profile: The Profile microservice
  ###################################
  profile:
    build:
      context: ./Profile
      dockerfile: profile.Dockerfile
    image: jiaxuanlai/profile:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/profile
      PYTHONUNBUFFERED: 1
    ports:
      - "5018:5018"
    networks:
      - esd-net      

  ###################################
  # StripePayment: The StripePayment microservice
  ###################################
  payment:
    build:
      context: ./StripePayment
      dockerfile: payment.Dockerfile
    image: jiaxuanlai/payment:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"
    networks:
      - esd-net

  ###################################
  # Add to Cart: The Add to Cart composite microservice
  ###################################
  addToCart:
    build:
      context: ./AddToCart
      dockerfile: addToCart.Dockerfile
    image: jiaxuanlai/addtocart:esd
    restart: always
    depends_on:
      - cart
      - cart_items
      - cart_items_customisation
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"
    networks:
      - esd-net      
