version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: drink_ingredients_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - drink_ingredients_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drink_ingredients_microservice
    restart: always
    ports:
      - "5006:5006"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@mysql_db/${MYSQL_DATABASE}
    networks:
      - drink_ingredients_network

networks:
  drink_network:
    driver: bridge

volumes:
  mysql_data: